---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/drone/drone-jsonnet-config

steps:
- name: build
  image: golang:1.11
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go test ./...
  - go build -o release/linux/amd64/drone-jsonnet-config github.com/drone/drone-jsonnet-config/cmd/drone-jsonnet-config
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      $secret: password
    repo: drone/drone-jsonnet
    username:
      $secret: username

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: upload
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      $secret: password
    spec: docker/manifest.tmpl
    username:
      $secret: username

trigger:
  event:
  - push

depends_on:
- amd64

---
kind: secret
type: external
data:
  password: "drone/docker#password"
  username: "drone/docker#username"

...
