FROM alpine:3.9

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Jsonnet Config" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000
ENV GODEBUG netdns=go

RUN apk add --no-cache ca-certificates

ADD release/linux/amd64/drone-jsonnet-config /bin/
ENTRYPOINT ["/bin/drone-jsonnet-config"]
